spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=movie_db
spring.datasource.password=movie_db123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

server.port=1111

spring.mvc.hiddenmethod.filter.enabled=true

logging.level.root=INFO
logging.level.ro.platformafilme=DEBUG